### PR TITLE
Added flash function and fixed toggle camera

### PR DESCRIPTION
**Pull request by adlanarifzr**
Please try before merge the PR

### CODE REVIEW

**Comment by allanwolski** [comment]
Waiting for this

**Comment by jcn2185** [comment]
Just tested this via:

```
  fast_qr_reader_view: ### TODO: Replace this when the version actually goes live.....
    git:
      url: https://github.com/facundomedica/fast_qr_reader_view.git
      ref: 5f3794cb515b4842d74373627f6de6019b3567c9
```

Works great. @adlanarifzr nice fix

**Comment by mettini** [comment]
Works for me too!

**Comment by facundomedica** [comment]
@adlanarifzr thanks for the PR! I didn't test it thoroughly but it seems to be well tested 😉

**Pull request merged**
